
title: Code.mil
email: code@dds.mil
description: An experiment in open source within the Department of Defense.

styles:
  - /assets/css/main.css
  - /assets/css/custom.css

scripts:
  - /assets/uswds/js/uswds.min.js
  - /assets/js/main.js

# Build settings
markdown: kramdown
remote_theme: uswds-jekyll

include:
  - '_pages'

plugins:
  - 'jekyll-remote-theme 

exclude:
  - 'build'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'robots.txt-for-beta.code.mil'
  - 'serve'
  - 'vendor'
